In [1]:
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px

import os
import os
import sys
import pandas as pd
from typing import List, Dict, Optional
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings

warnings.filterwarnings("ignore")
import plotly.express as px

In [2]:
dataset_path = r'C:\Users\TPWODL\New folder_Content\AutonomousDataAnalystAgent\data\raw\x_data.xlsx'

In [3]:
main_df = pd.read_excel(r'C:\Users\TPWODL\New folder_Content\AutonomousDataAnalystAgent\data\raw\x_data.xlsx')

In [4]:
df = main_df.copy()
df['DATE'] = pd.to_datetime(df['DATE'])
day_filter_data = df[df['DATE'] == '2025-11-25']

In [6]:
day_filter_data.columns

Index(['SL.NO', 'DATE', 'SHIFT DUTY', 'QUERY/REQUEST/COMPLAINT',
       'COMPLAINT DETAILS', 'COMPLAINT NUMBER', 'SECTION', 'SUB-DIVISION',
       'DIVISION', 'CIRCLE', 'COMPLAINT TYPE', 'CONSUMER NUMBER',
       'MOBILE NUMB', 'DEPT', 'CLOSED/OPEN', 'REMARKS', 'TWEET/LINK',
       'COMPLAINANT NAME', 'COMPLAINT RECEIVED TIME', 'RESPONSE TIME',
       'SECOND RESPONSE TIME', 'FINAL RESPONSE TIME',
       'FINAL RESPONSE DATE DD/MM/YYYY', 'PSCC/FG/TO', 'ARREARS',
       'REPEAT (Y / N)', 'FORWARDED TO', 'SENTIMENTS', 'NATURE OF TWEET',
       'ACTIONABLE/ NON ACTIONABLE', 'AGEING', 'SLAB', 'SLAB2', 'MINUTE'],
      dtype='object')

In [14]:
day_filter_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27 entries, 32154 to 32180
Data columns (total 34 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   SL.NO                           27 non-null     object
 1   DATE                            27 non-null     datetime64[ns]
 2   SHIFT DUTY                      27 non-null     object
 3   QUERY/REQUEST/COMPLAINT         27 non-null     object
 4   COMPLAINT DETAILS               27 non-null     object
 5   COMPLAINT NUMBER                4 non-null      object
 6   SECTION                         23 non-null     object
 7   SUB-DIVISION                    24 non-null     object
 8   DIVISION                        24 non-null     object
 9   CIRCLE                          24 non-null     object
 10  COMPLAINT TYPE                  27 non-null     object
 11  CONSUMER NUMBER                 8 non-null      object
 12  MOBILE NUMB                     2 non-null      object
 13  DEPT                            27 non-null     object
 14  CLOSED/OPEN                     27 non-null     object
 15  REMARKS                         27 non-null     object
 16  TWEET/LINK                      27 non-null     object
 17  COMPLAINANT NAME                27 non-null     object
 18  COMPLAINT RECEIVED TIME         27 non-null     object
 19  RESPONSE TIME                   27 non-null     object
 20  SECOND RESPONSE TIME            26 non-null     object
 21  FINAL RESPONSE TIME             15 non-null     object
 22  FINAL RESPONSE DATE DD/MM/YYYY  15 non-null     object
 23  PSCC/FG/TO                      7 non-null      object
 24  ARREARS                         4 non-null      object
 25  REPEAT (Y / N)                  0 non-null      object
 26  FORWARDED TO                    0 non-null      object
 27  SENTIMENTS                      0 non-null      object
 28  NATURE OF TWEET                 0 non-null      object
 29  ACTIONABLE/ NON ACTIONABLE      0 non-null      object
 30  AGEING                          0 non-null      float64
 31  SLAB                            0 non-null      object
 32  SLAB2                           0 non-null      object
 33  MINUTE                          27 non-null     float64
dtypes: datetime64[ns](1), float64(2), object(31)
memory usage: 7.4+ KB

In [ ]:
day_filter_data

(27, 34)

In [12]:
time_value = day_filter_data['COMPLAINT RECEIVED TIME']

In [17]:
day_filter_data['COMPLAINT TYPE'].value_counts()

COMPLAINT TYPE
Power Outage                  6
Pole Shifting / Lt Sagging    5
Others                        5
Low Voltage                   3
NSC                           2
Civil works                   2
No Power Supply               2
Safety                        1
Solar                         1
Name: count, dtype: int64

In [40]:
df = main_df.copy()
df['DATE'] = pd.to_datetime(df['DATE'])
day_filter_data = df[df['DATE'] == '2025-11-25']
power_outage_data = day_filter_data[(day_filter_data['COMPLAINT TYPE'] == 'Power Outage') | (day_filter_data['COMPLAINT TYPE'] == 'No Power Supply')]

In [22]:
time01 = power_outage_data['COMPLAINT RECEIVED TIME']
time02 = power_outage_data['FINAL RESPONSE TIME']

In [29]:
# Format time columns into AM/PM strings
time01 = power_outage_data['COMPLAINT RECEIVED TIME'].apply(lambda t: t.strftime("%I:%M %p") if pd.notnull(t) else "")
time02 = power_outage_data['FINAL RESPONSE TIME'].apply(lambda t: t.strftime("%I:%M %p") if pd.notnull(t) else "")

# Combine into the desired format
power_outage_data['TIME_RANGE'] = time01 + " TO " + time02

In [31]:
power_outage_data[['COMPLAINT RECEIVED TIME','FINAL RESPONSE TIME','TIME_RANGE']].head()

      COMPLAINT RECEIVED TIME FINAL RESPONSE TIME            TIME_RANGE
32155                01:00:00            07:35:00  01:00 AM TO 07:35 AM
32160                06:40:00            06:44:00  06:40 AM TO 06:44 AM
32164                10:35:00            10:36:00  10:35 AM TO 10:36 AM
32169                12:30:00            12:32:00  12:30 PM TO 12:32 PM
32173                13:56:00            16:33:00  01:56 PM TO 04:33 PM

In [ ]:
import pandas as pd
from datetime import datetime

# Convert time objects into datetime for subtraction
def to_datetime(t):
    if pd.isnull(t):
        return None
    return datetime.combine(datetime.today(), t)

# Apply conversion
start = power_outage_data['COMPLAINT RECEIVED TIME'].apply(to_datetime)
end   = power_outage_data['FINAL RESPONSE TIME'].apply(to_datetime)

# Calculate difference
power_outage_data['DURATION'] = (end - start)

# If you want the difference in minutes
power_outage_data['DURATION_MINUTES'] = power_outage_data['DURATION'].dt.total_seconds() / 60

# Preview
duretion_minit = power_outage_data[['COMPLAINT RECEIVED TIME','FINAL RESPONSE TIME','DURATION','DURATION_MINUTES']]

,COMPLAINT RECEIVED TIME,FINAL RESPONSE TIME,DURATION,DURATION_MINUTES
32155,01:00:00,07:35:00,0 days 06:35:00,395.0
32160,06:40:00,06:44:00,0 days 00:04:00,4.0
32164,10:35:00,10:36:00,0 days 00:01:00,1.0
32169,12:30:00,12:32:00,0 days 00:02:00,2.0
32173,13:56:00,16:33:00,0 days 02:37:00,157.0

In [35]:
import pandas as pd
from datetime import datetime

# Convert time objects into datetime for subtraction
def to_datetime(t):
    if pd.isnull(t):
        return None
    return datetime.combine(datetime.today(), t)

# Apply conversion
start = power_outage_data['COMPLAINT RECEIVED TIME'].apply(to_datetime)
end   = power_outage_data['FINAL RESPONSE TIME'].apply(to_datetime)

# Calculate difference in hours only
power_outage_data['DURATION_HOURS'] = (end - start).dt.total_seconds() / 3600

# Preview
print(power_outage_data[['COMPLAINT RECEIVED TIME','FINAL RESPONSE TIME','DURATION_HOURS']].head())

      COMPLAINT RECEIVED TIME FINAL RESPONSE TIME  DURATION_HOURS
32155                01:00:00            07:35:00        6.583333
32160                06:40:00            06:44:00        0.066667
32164                10:35:00            10:36:00        0.016667
32169                12:30:00            12:32:00        0.033333
32173                13:56:00            16:33:00        2.616667

In [36]:
power_outage_data[['COMPLAINT RECEIVED TIME','FINAL RESPONSE TIME','DURATION_HOURS']].head()

      COMPLAINT RECEIVED TIME FINAL RESPONSE TIME  DURATION_HOURS
32155                01:00:00            07:35:00        6.583333
32160                06:40:00            06:44:00        0.066667
32164                10:35:00            10:36:00        0.016667
32169                12:30:00            12:32:00        0.033333
32173                13:56:00            16:33:00        2.616667

In [ ]:
import pandas as pd
from datetime import datetime



df = main_df.copy()
df['DATE'] = pd.to_datetime(df['DATE'])
day_filter_data = df[df['DATE'] == '2025-11-25']
power_outage_data = day_filter_data[(day_filter_data['COMPLAINT TYPE'] == 'Power Outage') | (day_filter_data['COMPLAINT TYPE'] == 'No Power Supply')]

# Convert time objects into datetime for subtraction
def to_datetime(t):
    if pd.isnull(t):
        return None
    return datetime.combine(datetime.today(), t)

# Apply conversion
start = power_outage_data['COMPLAINT RECEIVED TIME'].apply(to_datetime)
end   = power_outage_data['FINAL RESPONSE TIME'].apply(to_datetime)

# Calculate difference in hours
power_outage_data['DURATION_HOURS'] = (end - start).dt.total_seconds() / 3600

# Round to nearest whole hour
power_outage_data['DURATION_HOURS_ROUNDED'] = power_outage_data['DURATION_HOURS'].round()

# If you want only integer hours (floor)
power_outage_data['DURATION_HOURS_INT'] = power_outage_data['DURATION_HOURS'].astype(int)

# Preview
power_outage_data[['COMPLAINT RECEIVED TIME','FINAL RESPONSE TIME','DURATION_HOURS','DURATION_HOURS_ROUNDED','DURATION_HOURS_INT']].head()

      COMPLAINT RECEIVED TIME FINAL RESPONSE TIME  DURATION_HOURS  \
32155                01:00:00            07:35:00        6.583333
32160                06:40:00            06:44:00        0.066667
32164                10:35:00            10:36:00        0.016667
32169                12:30:00            12:32:00        0.033333
32173                13:56:00            16:33:00        2.616667

       DURATION_HOURS_ROUNDED  DURATION_HOURS_INT
32155                     7.0                   6
32160                     0.0                   0
32164                     0.0                   0
32169                     0.0                   0
32173                     3.0                   2

In [38]:
power_outage_data[['COMPLAINT RECEIVED TIME','FINAL RESPONSE TIME','DURATION_HOURS','DURATION_HOURS_ROUNDED','DURATION_HOURS_INT']].head()

,COMPLAINT RECEIVED TIME,FINAL RESPONSE TIME,DURATION_HOURS,DURATION_HOURS_ROUNDED,DURATION_HOURS_INT
32155,01:00:00,07:35:00,6.583333,7.0,6
32160,06:40:00,06:44:00,0.066667,0.0,0
32164,10:35:00,10:36:00,0.016667,0.0,0
32169,12:30:00,12:32:00,0.033333,0.0,0
32173,13:56:00,16:33:00,2.616667,3.0,2

In [41]:
import pandas as pd
from datetime import datetime

df = main_df.copy()
df['DATE'] = pd.to_datetime(df['DATE'])
day_filter_data = df[df['DATE'] == '2025-11-25']
power_outage_data = day_filter_data[(day_filter_data['COMPLAINT TYPE'] == 'Power Outage') | (day_filter_data['COMPLAINT TYPE'] == 'No Power Supply')]

# Convert time objects into datetime for subtraction
def to_datetime(t):
    if pd.isnull(t):
        return None
    return datetime.combine(datetime.today(), t)

# Apply conversion
start = power_outage_data['COMPLAINT RECEIVED TIME'].apply(to_datetime)
end   = power_outage_data['FINAL RESPONSE TIME'].apply(to_datetime)

# Calculate difference in hours
power_outage_data['DURATION_HOURS'] = (end - start).dt.total_seconds() / 3600

# Round to nearest whole hour
power_outage_data['DURATION_HOURS_ROUNDED'] = power_outage_data['DURATION_HOURS'].round()

# If you want only integer hours (floor)
power_outage_data['DURATION_HOURS_INT'] = power_outage_data['DURATION_HOURS'].astype(int)

# Preview
power_outage_data[['COMPLAINT RECEIVED TIME','FINAL RESPONSE TIME','DURATION_HOURS','DURATION_HOURS_ROUNDED','DURATION_HOURS_INT']].head()

,COMPLAINT RECEIVED TIME,FINAL RESPONSE TIME,DURATION_HOURS,DURATION_HOURS_ROUNDED,DURATION_HOURS_INT
32155,01:00:00,07:35:00,6.583333,7.0,6
32160,06:40:00,06:44:00,0.066667,0.0,0
32164,10:35:00,10:36:00,0.016667,0.0,0
32169,12:30:00,12:32:00,0.033333,0.0,0
32173,13:56:00,16:33:00,2.616667,3.0,2

In [42]:
power_outage_data.columns

Index(['SL.NO', 'DATE', 'SHIFT DUTY', 'QUERY/REQUEST/COMPLAINT',
       'COMPLAINT DETAILS', 'COMPLAINT NUMBER', 'SECTION', 'SUB-DIVISION',
       'DIVISION', 'CIRCLE', 'COMPLAINT TYPE', 'CONSUMER NUMBER',
       'MOBILE NUMB', 'DEPT', 'CLOSED/OPEN', 'REMARKS', 'TWEET/LINK',
       'COMPLAINANT NAME', 'COMPLAINT RECEIVED TIME', 'RESPONSE TIME',
       'SECOND RESPONSE TIME', 'FINAL RESPONSE TIME',
       'FINAL RESPONSE DATE DD/MM/YYYY', 'PSCC/FG/TO', 'ARREARS',
       'REPEAT (Y / N)', 'FORWARDED TO', 'SENTIMENTS', 'NATURE OF TWEET',
       'ACTIONABLE/ NON ACTIONABLE', 'AGEING', 'SLAB', 'SLAB2', 'MINUTE',
       'DURATION_HOURS', 'DURATION_HOURS_ROUNDED', 'DURATION_HOURS_INT'],
      dtype='object')

In [57]:
close_open_hour = power_outage_data[['DIVISION','SUB-DIVISION', 'SHIFT DUTY', 'CLOSED/OPEN', 'DURATION_HOURS_INT']]

In [58]:
close_open_hour

            DIVISION SUB-DIVISION SHIFT DUTY CLOSED/OPEN  DURATION_HOURS_INT
32155        BARGARH    BARGARH-1          C      Closed                   6
32160  BRAJARAJNAGAR     BELPAHAR          A      Closed                   0
32164  BRAJARAJNAGAR     BELPAHAR          A      Closed                   0
32169  BRAJARAJNAGAR     BELPAHAR          A      Closed                   0
32173           KWED     JUNAGARH          A      Closed                   2
32174  BRAJARAJNAGAR     BELPAHAR          A      Closed                   0
32177           KWED     JUNAGARH          B      Closed                   0
32178        NUAPADA      KHARIAR          B      Closed                   0

In [60]:
import pandas as pd

# Define a function to classify values with inclusive boundaries
def classify_duration(x):
    if x <= 2:
        return "<2"
    elif 2 < x <= 4:
        return "2<4"
    elif 4 < x <= 8:
        return "4<8"
    elif x >= 8:
        return ">8"
    else:
        return None

# Apply function to create new column
close_open_hour["DURATION_RANGE"] = close_open_hour["DURATION_HOURS_INT"].apply(classify_duration)

In [61]:
close_open_hour

,DIVISION,SUB-DIVISION,SHIFT DUTY,CLOSED/OPEN,DURATION_HOURS_INT,DURATION_RANGE
32155,BARGARH,BARGARH-1,C,Closed,6,4<8
32160,BRAJARAJNAGAR,BELPAHAR,A,Closed,0,<2
32164,BRAJARAJNAGAR,BELPAHAR,A,Closed,0,<2
32169,BRAJARAJNAGAR,BELPAHAR,A,Closed,0,<2
32173,KWED,JUNAGARH,A,Closed,2,<2
32174,BRAJARAJNAGAR,BELPAHAR,A,Closed,0,<2
32177,KWED,JUNAGARH,B,Closed,0,<2
32178,NUAPADA,KHARIAR,B,Closed,0,<2