In [39]:
print("hallow world")

hallow world

In [40]:
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
from datetime import datetime, timedelta, time
import os
import os
import sys
import pandas as pd
from typing import List, Dict, Optional
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings
import random
import re

warnings.filterwarnings("ignore")
import plotly.express as px

In [41]:
dataset_path = r'C:\Users\LENOVO\MachineLearningProjects\AutonomousDataAnalystAgent\data\raw_path\x_data.xlsx'

In [42]:
new_df = pd.read_excel(r'C:\Users\LENOVO\MachineLearningProjects\AutonomousDataAnalystAgent\data\raw_path\x_data.xlsx')

In [43]:
new_df.shape

(32873, 34)

In [44]:
# Extract text after "at" (case-insensitive)
new_df['Location'] = (
    new_df['COMPLAINT DETAILS']
    .astype(str)
    .str.extract(r'(?i)\bat\s+(.*)')
    [0]   # str.extract returns a DataFrame, so take first column
    .str.strip()  # remove leading/trailing spaces
    .fillna('NA') # handle missing values
)

# Keep only rows where Location is NOT "NA" (i.e., where data was found)
df_final = new_df[new_df['Location'] != 'NA'].copy()

In [54]:
location_df = df_final[['Location', 'SUB-DIVISION']]

In [55]:
location_df

                                                Location       SUB-DIVISION
5                              Haragouirbihar,Sambalpur.  SDO-1, AINTHAPALI
11                                  pradhanpali  bargarh          BARGARH-1
14     sambalpur. Mr. Amit is asked to share the cont...                NaN
25                                - Sinapali dist Nupada            KHARIAR
26                                   sindhekela bolangir          TITLAGARH
...                                                  ...                ...
32866                                     rengali basti.            RENGALI
32867                                     rengali basti.            RENGALI
32868                                             kikia.            KESINGA
32870                               ujalpur, sundargarh.            UJALPUR
32872                                          BALAGAON.          CHARBAHAL

[8780 rows x 2 columns]

In [48]:
vilage_df = pd.DataFrame(location_df)

In [49]:
vilage_df

                                                Location       SUB-DIVISION
5                              Haragouirbihar,Sambalpur.  SDO-1, AINTHAPALI
11                                  pradhanpali  bargarh          BARGARH-1
14     sambalpur. Mr. Amit is asked to share the cont...                NaN
25                                - Sinapali dist Nupada            KHARIAR
26                                   sindhekela bolangir          TITLAGARH
...                                                  ...                ...
32866                                     rengali basti.            RENGALI
32867                                     rengali basti.            RENGALI
32868                                             kikia.            KESINGA
32870                               ujalpur, sundargarh.            UJALPUR
32872                                          BALAGAON.          CHARBAHAL

[8780 rows x 2 columns]

In [50]:
# Save to Excel
vilage_df.to_excel('output_file.xlsx', index=False)

In [ ]:
vilage_df.sample(n=5, random_state=42)

                                               Location
3463                                   Lanjhigarh town.
4192                        Consumer No :\t413122030402
3783  Kohall Sahi, Saida GP, Barkote block, Deogarh ...
8053                           the PSC pole connection.
4675                         Consumer No : 911111260179

In [ ]:
new_df.columns

Index(['SL.NO', 'DATE', 'SHIFT DUTY', 'QUERY/REQUEST/COMPLAINT',
       'COMPLAINT DETAILS', 'COMPLAINT NUMBER', 'SECTION', 'SUB-DIVISION',
       'DIVISION', 'CIRCLE', 'COMPLAINT TYPE', 'CONSUMER NUMBER',
       'MOBILE NUMB', 'DEPT', 'CLOSED/OPEN', 'REMARKS', 'TWEET/LINK',
       'COMPLAINANT NAME', 'COMPLAINT RECEIVED TIME', 'RESPONSE TIME',
       'SECOND RESPONSE TIME', 'FINAL RESPONSE TIME',
       'FINAL RESPONSE DATE DD/MM/YYYY', 'PSCC/FG/TO', 'ARREARS',
       'REPEAT (Y / N)', 'FORWARDED TO', 'SENTIMENTS', 'NATURE OF TWEET',
       'ACTIONABLE/ NON ACTIONABLE', 'AGEING', 'SLAB', 'SLAB2', 'MINUTE',
       'Location'],
      dtype='object')

In [ ]:
"""
Location Extractor for Power Outage Data
Extracts structured location information from raw text data
"""

import re
import json

# Raw data
raw_data = """
Bhikapada village under Kutunia panchayat and Geerjapada village under Malidihi panchayat of Rajgangpur block due to burning of transformer.
Kharamunda village Bijepur block. (Bargarh dist)
Karangamal village lift point under Boden block of Nuapada dist.
Srirampada, Po-Sahala, Sonepur dist.
Dharamgarh area citing increasing theft cases.(Kalahandi dist)
Nidhenpali village of Lupursingha GP under Bheden block, Bargarh dist.
Jhengnadihi village of Bhengarajpur GP under Paikmal. (Bargarh dist)
Tikrapada area, Bolangir. (Section-2)
Sarabhal, Jharsuguda
Thuamul, Rampur block Bhawnipatna Kahalandi
Nuagaon block  since 7:45 AM ,Dist sundargarh
chhend  Rourkela.
Murusundha, Lupursingha Fidder, Salebhata Section, Bolangir dist.
Hirakud area  since 12HRS.
Desil village, Titlagarh since yesterday 9 PM.
Jharmunda and Bijubandha slum of Tangarpali area, South Rourkela.
"""

def extract_locations(text):
    """
    Extract location information from the text
    Returns a list of dictionaries with structured location data
    """
    locations = []
    lines = text.strip().split('\n')
    
    for line in lines:
        if not line.strip():
            continue
            
        location_data = {
            'villages': [],
            'panchayat': None,
            'block': None,
            'district': None,
            'area': None,
            'additional_info': [],
            'original_text': line.strip()
        }
        
        # Extract district
        dist_match = re.search(r'(\w+)\s+dist', line, re.IGNORECASE)
        if dist_match:
            location_data['district'] = dist_match.group(1).strip()
        
        dist_match2 = re.search(r'Dist\s+(\w+)', line, re.IGNORECASE)
        if dist_match2:
            location_data['district'] = dist_match2.group(1).strip()
        
        # Extract block
        block_match = re.search(r'(\w+)\s+block', line, re.IGNORECASE)
        if block_match:
            location_data['block'] = block_match.group(1).strip()
        
        # Extract villages
        village_matches = re.findall(r'(\w+)\s+village', line, re.IGNORECASE)
        location_data['villages'] = [v.strip() for v in village_matches]
        
        # Extract panchayat
        panchayat_match = re.search(r'(\w+)\s+panchayat', line, re.IGNORECASE)
        if panchayat_match:
            location_data['panchayat'] = panchayat_match.group(1).strip()
        
        # Extract GP (Gram Panchayat)
        gp_match = re.search(r'(\w+)\s+GP', line, re.IGNORECASE)
        if gp_match:
            location_data['panchayat'] = gp_match.group(1).strip()
        
        # Extract area
        area_match = re.search(r'(\w+)\s+area', line, re.IGNORECASE)
        if area_match:
            location_data['area'] = area_match.group(1).strip()
        
        # Extract additional location names (before commas or specific keywords)
        # This captures places like "Sarabhal", "Chhend", etc.
        simple_location = re.match(r'^([A-Za-z\s]+),', line)
        if simple_location and not location_data['villages']:
            location_data['area'] = simple_location.group(1).strip()
        
        # Extract additional info like "slum", "lift point", etc.
        if 'slum' in line.lower():
            location_data['additional_info'].append('slum')
        if 'lift point' in line.lower():
            location_data['additional_info'].append('lift point')
        
        locations.append(location_data)
    
    return locations

def print_locations_summary(locations):
    """Print a clean summary of all locations"""
    print("=" * 80)
    print("EXTRACTED LOCATIONS SUMMARY")
    print("=" * 80)
    
    all_places = set()
    
    for i, loc in enumerate(locations, 1):
        print(f"\n{i}. ", end="")
        
        location_parts = []
        
        # Villages
        if loc['villages']:
            for village in loc['villages']:
                all_places.add(village)
            location_parts.append(f"Villages: {', '.join(loc['villages'])}")
        
        # Area
        if loc['area']:
            all_places.add(loc['area'])
            location_parts.append(f"Area: {loc['area']}")
        
        # Panchayat
        if loc['panchayat']:
            all_places.add(loc['panchayat'])
            location_parts.append(f"Panchayat: {loc['panchayat']}")
        
        # Block
        if loc['block']:
            all_places.add(loc['block'])
            location_parts.append(f"Block: {loc['block']}")
        
        # District
        if loc['district']:
            all_places.add(loc['district'])
            location_parts.append(f"District: {loc['district']}")
        
        # Additional info
        if loc['additional_info']:
            location_parts.append(f"Type: {', '.join(loc['additional_info'])}")
        
        print(" | ".join(location_parts))
    
    print("\n" + "=" * 80)
    print(f"UNIQUE PLACES FOUND: {len(all_places)}")
    print("=" * 80)
    print(", ".join(sorted(all_places)))
    print()

def export_to_csv(locations, filename='locations.csv'):
    """Export locations to CSV file"""
    import csv
    
    with open(filename, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(['Villages', 'Panchayat', 'Block', 'District', 'Area', 'Additional Info', 'Original Text'])
        
        for loc in locations:
            writer.writerow([
                ', '.join(loc['villages']) if loc['villages'] else '',
                loc['panchayat'] or '',
                loc['block'] or '',
                loc['district'] or '',
                loc['area'] or '',
                ', '.join(loc['additional_info']) if loc['additional_info'] else '',
                loc['original_text']
            ])
    
    print(f"✓ Data exported to {filename}")

def export_to_json(locations, filename='locations.json'):
    """Export locations to JSON file"""
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(locations, f, indent=2, ensure_ascii=False)
    
    print(f"✓ Data exported to {filename}")

# Main execution
if __name__ == "__main__":
    # Extract locations
    locations = extract_locations(raw_data)
    
    # Print summary
    print_locations_summary(locations)
    
    # Export to files
    export_to_csv(locations, 'locations.csv')
    
    print("\n" + "=" * 80)
    print("EXTRACTION COMPLETE!")
    print("=" * 80)

================================================================================
EXTRACTED LOCATIONS SUMMARY
================================================================================

1. Villages: Bhikapada, Geerjapada | Panchayat: Kutunia | Block: Rajgangpur

2. Villages: Kharamunda | Block: Bijepur | District: Bargarh

3. Villages: Karangamal | Block: Boden | District: Nuapada | Type: lift point

4. Area: Srirampada | District: Sonepur

5. Area: Dharamgarh | District: Kalahandi

6. Villages: Nidhenpali | Panchayat: Lupursingha | Block: Bheden | District: Bargarh

7. Villages: Jhengnadihi | Panchayat: Bhengarajpur | District: Bargarh

8. Area: Tikrapada area

9. Area: Sarabhal

10. Area: Thuamul | Block: Rampur

11. Block: Nuagaon | District: sundargarh

12.

13. Area: Murusundha | District: Bolangir

14. Area: Hirakud

15. Villages: Desil

16. Area: Jharmunda and Bijubandha slum of Tangarpali area | Type: slum

================================================================================
UNIQUE PLACES FOUND: 30
================================================================================
Bargarh, Bheden, Bhengarajpur, Bhikapada, Bijepur, Boden, Bolangir, Desil, Dharamgarh, Geerjapada, Hirakud, Jharmunda and Bijubandha slum of Tangarpali area, Jhengnadihi, Kalahandi, Karangamal, Kharamunda, Kutunia, Lupursingha, Murusundha, Nidhenpali, Nuagaon, Nuapada, Rajgangpur, Rampur, Sarabhal, Sonepur, Srirampada, Thuamul, Tikrapada area, sundargarh

✓ Data exported to locations.csv

================================================================================
EXTRACTION COMPLETE!
================================================================================

In [ ]:
"""
Location Extractor for Power Outage Data
Extracts structured location information from raw text data
"""

import re
import json

# Raw data
raw_data = """
Bhikapada village under Kutunia panchayat and Geerjapada village under Malidihi panchayat of Rajgangpur block due to burning of transformer.
Kharamunda village Bijepur block. (Bargarh dist)
Karangamal village lift point under Boden block of Nuapada dist.
Srirampada, Po-Sahala, Sonepur dist.
Dharamgarh area citing increasing theft cases.(Kalahandi dist)
Nidhenpali village of Lupursingha GP under Bheden block, Bargarh dist.
Jhengnadihi village of Bhengarajpur GP under Paikmal. (Bargarh dist)
Tikrapada area, Bolangir. (Section-2)
Sarabhal, Jharsuguda
Thuamul, Rampur block Bhawnipatna Kahalandi
Nuagaon block  since 7:45 AM ,Dist sundargarh
chhend  Rourkela.
Murusundha, Lupursingha Fidder, Salebhata Section, Bolangir dist.
Hirakud area  since 12HRS.
Desil village, Titlagarh since yesterday 9 PM.
Jharmunda and Bijubandha slum of Tangarpali area, South Rourkela.
"""

def extract_locations(text):
    """
    Extract all location names from the text
    Returns a list of location strings in simple format
    """
    location_lines = []
    lines = text.strip().split('\n')
    
    for line in lines:
        if not line.strip():
            continue
        
        locations = []
        
        # Extract villages (word before "village")
        village_matches = re.findall(r'(\w+)\s+village', line, re.IGNORECASE)
        locations.extend([v.strip() for v in village_matches])
        
        # Extract panchayats (word before "panchayat" or "GP")
        panchayat_matches = re.findall(r'(\w+)\s+(?:panchayat|GP)', line, re.IGNORECASE)
        locations.extend([p.strip() for p in panchayat_matches])
        
        # Extract blocks (word before "block")
        block_matches = re.findall(r'(\w+)\s+block', line, re.IGNORECASE)
        locations.extend([b.strip() for b in block_matches])
        
        # Extract districts (word before "dist" or after "Dist")
        dist_matches = re.findall(r'(?:(\w+)\s+dist|Dist\s+(\w+))', line, re.IGNORECASE)
        for match in dist_matches:
            dist_name = match[0] if match[0] else match[1]
            if dist_name:
                locations.append(dist_name.strip())
        
        # Extract areas (word before "area")
        area_matches = re.findall(r'(\w+)\s+area', line, re.IGNORECASE)
        locations.extend([a.strip() for a in area_matches])
        
        # Extract location names that appear before commas at start of line
        start_match = re.match(r'^([A-Za-z]+)\s*,', line)
        if start_match:
            loc_name = start_match.group(1).strip()
            if loc_name.lower() != 'po':  # Skip "Po-" prefix
                locations.append(loc_name)
        
        # Extract "word1 and word2" patterns (like "Jharmunda and Bijubandha")
        and_matches = re.findall(r'(\w+)\s+and\s+(\w+)', line, re.IGNORECASE)
        for match in and_matches:
            # Skip common words
            if match[0].lower() not in ['slum', 'of', 'under', 'since']:
                locations.append(match[0].strip())
            if match[1].lower() not in ['slum', 'of', 'under', 'since']:
                locations.append(match[1].strip())
        
        # Extract location after "Po-"
        po_match = re.search(r'Po-(\w+)', line, re.IGNORECASE)
        if po_match:
            locations.append(po_match.group(1).strip())
        
        # Extract city names (specific known cities in the region)
        city_patterns = ['Rourkela', 'Bhawanipatna', 'Bhawnipatna', 'Titlagarh', 'Jharsuguda', 'Bolangir']
        for city in city_patterns:
            if city.lower() in line.lower() and city not in locations:
                locations.append(city)
        
        # Remove duplicates and unwanted words while preserving order
        seen = set()
        unique_locations = []
        unwanted = {'panchayat', 'village', 'block', 'dist', 'gp', 'area', 'slum', 'of', 'under', 'po', 'since', 'section'}
        
        for loc in locations:
            if loc.lower() not in seen and loc.lower() not in unwanted:
                seen.add(loc.lower())
                unique_locations.append(loc)
        
        if unique_locations:
            location_lines.append(', '.join(unique_locations) + '.')
    
    return location_lines

def print_locations(locations):
    """Print locations in simple format"""
    print("=" * 80)
    print("EXTRACTED LOCATIONS")
    print("=" * 80)
    print()
    
    for loc_line in locations:
        print(loc_line)
    
    print()
    print("=" * 80)

def save_to_file(locations, filename='locations.txt'):
    """Save locations to text file"""
    with open(filename, 'w', encoding='utf-8') as f:
        for loc_line in locations:
            f.write(loc_line + '\n')
    
    print(f"✓ Locations saved to {filename}")

# Main execution
if __name__ == "__main__":
    # Extract locations
    locations_exact_df = extract_locations(raw_data)
    
    # Print locations
    print_locations(locations_exact_df)
    
    # Save to file
    save_to_file(locations_exact_df, 'locations_exact_df.txt')
    
    print("\n" + "=" * 80)
    print("EXTRACTION COMPLETE!")
    print("=" * 80)

================================================================================
EXTRACTED LOCATIONS
================================================================================

Bhikapada, Geerjapada, Kutunia, Malidihi, Rajgangpur.
Kharamunda, Bijepur, Bargarh.
Karangamal, Boden, Nuapada.
Sonepur, Srirampada, Sahala.
Kalahandi, Dharamgarh.
Nidhenpali, Lupursingha, Bheden, Bargarh.
Jhengnadihi, Bhengarajpur, Bargarh.
Tikrapada, Bolangir.
Sarabhal, Jharsuguda.
Rampur, Thuamul, Bhawnipatna.
Nuagaon, sundargarh.
Rourkela.
Bolangir, Murusundha.
Hirakud.
Desil, Titlagarh.
Tangarpali, Jharmunda, Bijubandha, Rourkela.

================================================================================
✓ Locations saved to locations_exact_df.txt

================================================================================
EXTRACTION COMPLETE!
================================================================================

In [ ]:
"""
Location Extractor for Power Outage Data
Extracts structured location information from raw text data
"""

import re
import json



def extractlocations(vilage_df):
    """
    Extract all location names from the text
    Returns a list of location strings in simple format
    """
    location_lines = []
    
    # Convert DataFrame to string if it's a DataFrame
    if hasattr(vilage_df, 'to_string'):
        text_data = vilage_df.to_string()
    else:
        text_data = str(vilage_df)
    
    lines = text_data.strip().split('\n')
    
    for line in lines:
        if not line.strip():
            continue
        
        locations = []
        
        # Extract villages (word before "village")
        village_matches = re.findall(r'(\w+)\s+village', line, re.IGNORECASE)
        locations.extend([v.strip() for v in village_matches])
        
        # Extract panchayats (word before "panchayat" or "GP")
        panchayat_matches = re.findall(r'(\w+)\s+(?:panchayat|GP)', line, re.IGNORECASE)
        locations.extend([p.strip() for p in panchayat_matches])
        
        # Extract blocks (word before "block")
        block_matches = re.findall(r'(\w+)\s+block', line, re.IGNORECASE)
        locations.extend([b.strip() for b in block_matches])
        
        # Extract districts (word before "dist" or after "Dist")
        dist_matches = re.findall(r'(?:(\w+)\s+dist|Dist\s+(\w+))', line, re.IGNORECASE)
        for match in dist_matches:
            dist_name = match[0] if match[0] else match[1]
            if dist_name:
                locations.append(dist_name.strip())
        
        # Extract areas (word before "area")
        area_matches = re.findall(r'(\w+)\s+area', line, re.IGNORECASE)
        locations.extend([a.strip() for a in area_matches])
        
        # Extract location names that appear before commas at start of line
        start_match = re.match(r'^([A-Za-z]+)\s*,', line)
        if start_match:
            loc_name = start_match.group(1).strip()
            if loc_name.lower() != 'po':  # Skip "Po-" prefix
                locations.append(loc_name)
        
        # Extract "word1 and word2" patterns (like "Jharmunda and Bijubandha")
        and_matches = re.findall(r'(\w+)\s+and\s+(\w+)', line, re.IGNORECASE)
        for match in and_matches:
            # Skip common words
            if match[0].lower() not in ['slum', 'of', 'under', 'since']:
                locations.append(match[0].strip())
            if match[1].lower() not in ['slum', 'of', 'under', 'since']:
                locations.append(match[1].strip())
        
        # Extract location after "Po-"
        po_match = re.search(r'Po-(\w+)', line, re.IGNORECASE)
        if po_match:
            locations.append(po_match.group(1).strip())
        
        # Extract city names (specific known cities in the region)
        city_patterns = ['Rourkela', 'Bhawanipatna', 'Bhawnipatna', 'Titlagarh', 'Jharsuguda', 'Bolangir']
        for city in city_patterns:
            if city.lower() in line.lower() and city not in locations:
                locations.append(city)
        
        # Remove duplicates and unwanted words while preserving order
        seen = set()
        unique_locations = []
        unwanted = {'panchayat', 'village', 'block', 'dist', 'gp', 'area', 'slum', 'of', 'under', 'po', 'since', 'section'}
        
        for loc in locations:
            if loc.lower() not in seen and loc.lower() not in unwanted:
                seen.add(loc.lower())
                unique_locations.append(loc)
        
        if unique_locations:
            location_lines.append(', '.join(unique_locations) + '.')
    
    return location_lines

def print_locations(locations):
    """Print locations in simple format"""
    print("=" * 80)
    print("EXTRACTED LOCATIONS")
    print("=" * 80)
    print()
    
    for loc_line in locations:
        print(loc_line)
    
    print()
    print("=" * 80)

def save_to_file(locations, filename='locations.txt'):
    """Save locations to text file"""
    with open(filename, 'w', encoding='utf-8') as f:
        for loc_line in locations:
            f.write(loc_line + '\n')
    
    print(f"✓ Locations saved to {filename}")

# Main execution
if __name__ == "__main__":
    # Extract locations
    locations_exact_df = extractlocations(vilage_df)
    
    # Print locations
    print_locations(locations_exact_df)
    
    # Save to file
    save_to_file(locations_exact_df, 'locations_exact_df.txt')
    
    print("\n" + "=" * 80)
    print("EXTRACTION COMPLETE!")
    print("=" * 80)

================================================================================
EXTRACTED LOCATIONS
================================================================================

Sinapali.
Bolangir.
from.
Makraguda, Golamunda, Kalahandi.
Rourkela.
Nupada.
Rourkela.
Rourkela.
Rourkela.
Rourkela.
Jharsuguda.
Rourkela.
Rourkela.
Rourkela.
kapharakhol.
town.
bolangir.
Rourkela.
Jharsuguda.
sambalpur.
huma, dhama, subdivision.
sundargarh.
bhainsa, patnagarh, bolangir.
agalpur, loisingha, bolangir.
kermira, jharsuguda.
subarnapur.
kuramunda, Rourkela.
kirajhola, boden, nupada.
kundukela.
villagr, saipali.
jharsuguda.
sambalpur, ainthapali.
bargarh.
bolangir.
loisingha, Bolangir.
para, Bolangir.
117, kendumundi.
Kushmel, Chatamakhana, Bolangir.
tulasinagar, Bolangir.
palkudar, deogarh.
Bolangir.
rugudipada, Bolangir.
Similipal.
sambalpur.
collage, Jharsuguda.
jharsuguda.
bhainatora, ambabhona, bargarh.
koida, sundargarh.
kuarmunda.
kalimandir, Jharsuguda.
LAHANDA.
sundargarh.
LAHANDA.
mushapali, komana, Nuapada.
Gurundia, sundargarh.
Junagarh.
Rourkela.
BONAI.
bolangir.
bolangir.
Rairakhol.
kanjrima.
bhalupita, patnagarh.
budhimara, radikhol, sambalpur.
lakshanpur, jharshuguda.
kansbahal.
batagaan, naktideol.
Bargarh.
feeder.
budhikhamria, rairakhol.
bolangir.
burla.
birmaharajpur, the.
rampur, barpili.
jharkanta, jharsuguda.
jayantapur.
palsada, boden, nupada.
jaypatna, murkhuda, Bolangir.
baragrh.
nupada.
garposh, Rourkela.
rengali.
pardhapali.
lane.
baragrh.
kirajhol, boden, nupada.
bhawanipatna.
sohela, dungripali, sonepur.
Lanchigarh.
Lanchigarh.
bareipalichowk.
Bejamunda, Gosala.
Bejamunda, Gosala.
goshala.
barbahali, hemgir.
Dungripali, the.
deogarh.
Bhawanipatna.
bargarh.
kadamdaha, telabani, Deogarh.
jharshuguda.
attabira.
kharaiar, duajhar.
rayagada.
rasalpadar, gaisilat.
Enclave.
Bolangir.
maneswar.
bhawanipatna.
Rourkela.
Khalguda, Lanjigarh.
sundargarh.
telibandh.
larambha, attabira.
bhanbahal.
Relatu, Koida, sunadrgarh.
sundargarh.
Bargarh.
brajanagar.
anthapali, also.
278.
bargarh.
pada.
rairakhol.
Bhawanipatan.
DHANUPALI.
bonai, sundargarh.
chudapudug, rairakhol, sambalpur.
sadhupali, sohela.
Goindamunda, kalahandi.
kirajhola, boden, nupada.
menda, bolangir.
Nagar, khalapada, Mahalaxmi, Bolangir.
Uparbahal, Banei.
clock.
Rourkela.
pada, Bhawanipatna.
Khalandi, Kendubahali.
Tableie, Maneswar.
sinapali, khariar.
Bolangir.
barpali.
sundargarh.
Jharbeda, Kuarmunda, Kacharu.
Sambalpur.
pur.
Raisalpadar, gaisilet.
lathor.
karlamunda, Kalahandi, Madanpur.
Kendumal, Gaisilet.
Bolangir.
Nuapada.
sakhipada.
sakhipada.
tangarpali.
pada, gounthiya, Jharsuguda.
badabharmani, ghantapali.
Lanjigarh, panchyat.
bargarh.
Biramaharajpur.
larki, nuapada.
jharsuguda.
pokharasaleh, kolabira, Jharsuguda.
Dholapada, Tileibani, Deogarh, is, month, rest.
Jada, Pankadidhi, Gurundia, Sundargarh.
Manko, Lathikata, Sundargarh.
Bharsuja, Agalpur, Bolangir.
jharsuguda.
Rourkela.
bargarh.
jharsuguda, Debadhi.
Bargarh.
Charbahal, Junagarh, Kalahandi.
Bargarh.
Bargarh.
Turla, Khaprakhol, Bolangir.
jharsugura.
Larambha, Bargarh.
bargarh.
agalpur, Bolangir.
panchyat.
gopiguda, lanjigarh, Bhawanipatna.
panchyat, Bolangir.
himgir, sundargarh.
birmitrapur.
chowk.
bargarh.
Gandapali, Bharsuja, Agalpur, Bolangir.
Sisuparna, Rairakhol, Sambalpur, Patakhaman.
Lupursingha, Bargarh.
Kalahandi.
Kandetara, Komana, Nuapada.
Boudh, Rajanpali.
nupada.
Balangir.
Dangiabahal.
Jharsuguda, Brajarajnagar.
Benagaon, Lanjigarh, Kalahandi, transformer, cables.
Sambalpur.
Bolangir.
Adhapara, Lakhanpur, Jharsuguda.
Sambalpur.
A, Agalpur, Bolangir.
Sambalpur.
Dhenkanal.
Katurkata, Barpali, bargarh.
delay, Jharsuguda.
Harijanapada, Belakhandi, Kalahandi.
Badheimunda, Jharsuguda.
Bhubaneswarpur, Paikamal, Bargarh.
Khujenpali, Bolangir.
Bolangir, Tikrapada.
Sambalpur, Ainthapali.
Jharsuguda.
ladpada, Kuchinda, Sambalpur.
Sonepur.
Sonepur, Binka.
Bhawanipatna.
Bhejipadar, Kikia, Kalahandi.
Talabhanra, Belakhandi, Kalahandi.
Budharaja.
Chhelkhai, Rota, Agalpur, Bolangir.
Tandabira, Daincha, Naktideula, Sambalpur.
gobindapalli.
balangri.
jharshuguda.
rourkela.
boudh.
boudh.
down, damaged, Rourkela.
aleikera, sundargarh.
Rourkela.
Padmapur, Reamal, Deogarh.
Sonepur.
Bondamunda, Rourkela.
Reamal, Deogarh.
Reamal, Debagarh.
Jharsuguda.
Kesinga, kalahandi, Tundla.
Bargarh, Ladarpali.
Kalahandi, Rampur.
line, Bolangir.
Bolangir.
Bharsuja, Agalpur, Bolangir.
Jharsuguda.
Khemesara, Barpali, Bargarh.
Kalahandi, Rampur.
Urladani, Rampur, Kalahandi.
Bindupur, Naktideul, Sabalpur.
Bolangir.
Garjanbahal.
Kanoshibahal, 526, Deogarh.
boudh.
Mundapada, Boudh.
Kalahandi.
Jharsuguda.
Bargarh, Karapada.
Hatipali, Kuchinda, Sambalpur.
Duduka, Agalpur, Bolangir.
Rourkela.
Modipada.
bolangri.
baragarh.
Sundargarh, Jamunadipa.
Nabarangpur.
Asannali, Basalai, Barkote, Deogarh.
Deogaon, Bolangir, Bandhapada.
Township, Rourkela.
Hotel.
Khedapali.
Majhapada, Buchukupada, Sundargarh.
Saintala, Bolangir.
Madalia, Saruali, Barkote, Deogarh.
Tandabira, Sambalpur, Daincha.
Kumarkeli, Mahada, Ulunda, Sonepur.
Godamal, Utuniyam, Riyamal, Deogarh.
Temri, Paikmal, Bargarh.
Basti, Jharsuguda.
Pakhanmunda, Kameimunda, Turekela, Bolangir.
Karamunda, Kalahandi.
Sonepur, Lachhipur.
Deogarh.
Bhikapada, Geerjapada, Kutunia, Malidihi, Rajgangpur.
Kharamunda, Bijepur, Bargarh.
Karangamal, Boden, Nuapada.
Sonepur, Sahala.
Kalahandi, Dharamgarh.
Nidhenpali, Lupursingha, Bheden, Bargarh.
Jhengnadihi, Bhengarajpur, Bargarh.
Tikrapada, Bolangir.
Jharsuguda.
Rampur, Bhawnipatna.
Nuagaon, sundargarh.
Rourkela.
Bolangir.
Hirakud.
Desil, Titlagarh.
Tangarpali, Jharmunda, Bijubandha, Rourkela.
Bolangir.
Bandhupala, Titlagarh.
Bhawanipatna.
Tumuripani, Jharbandh, Bargarh.
Bargarh.
Dudukijharia, Paikmal, Bargarh.
Bahadurpadar, Kesinga, Kalahandi.
Thebara, Bhaunrakhola, Lakhanpur, Jharsuguda.
BIJEPUR, BARGARH.
Kalahandi, Manjheri.
nearby, Utunia, Reamal, Deogarh, 5.
Jharbandh, Bargarh.
Keonjhar.
Deogarh.
Modipada.
rourkela, jagada.
Barkote.
banchipali, kapharakhol, Bolangir.
nuagaon.
badmal, rairakhol.
estate, Rourkela.
pokharasaleh, kolabira, Jharsuguda.
Kalahandi, naktiguda.
subdivision.
bolangir.
sambalpur.
sinapali, khariar.
mursundha, salebhata, Bolangir.
hirakud.
brajrajnagar.
jharband, bragarh.
bolangir, Titlagarh.
nagar.
crossing, Jharsuguda.
Boudh, river, no, Manamunda, Kantamal.
Bolangir.
Sarbahal, Jharsuguda.
Sambalpur.
Sinapali, Nuapada.
badadhara, Ambabhona, Bargarh.
Kalahandi, Tundla.
Sriram, Jamakhunta, Bangomunda, Bolangir.
Lanjigarh, Kalahandi.
Sarliguda.
Kokonara, Paikmaal, Bargarh.
Temri, Paikmal, Bargarh.
Kalahandi, Behera.
Taladhipapara, Bhatli, Bargarh.
Kalahandi, Behera.
SOHELA.
Sundargarh.
tulagaon, Kalahandi.
Jharsuguda.
sundargarh.
deogarh, kansar.
bolangir.
rairakhol.
jharial, bangomunda, Bolangir.
Tilajodi, Bhawanipatana, Bhanagapada, Harijanpada.
Old.
Tilkamal, Gudvela, Bolangir.
Ainthapali.
Sundargarh.
RANGIADHIPA.
Utuniam, Riyamal, Deogarh.
Pithinda, Lakhanpur, Jharsuguda.
Badbausen, Bargarh.
Modipada.
Fulerpali, Bijepur, Bargarh.
Soleguda, Sole, Sundargarh.
Rourkela.
Bolangir.
Budhakata.
nuagaon.
733.
Boudh, Kantamal.
Jharsuguda.
Modipada.
Bargarh.
pudherpur, padmapur, Bargarh.
Budeljore.
Rourkela.
turekela, bolangir.
Bolangir.
brajrajnagar.
Budeljore.
Badbausen, Bargarh.
Sundargarh.
Badalipada, Kutra, Sundargarh.
Barpali, Bargarh.
Sundargarh.
Sundargarh.
Bhawanipatna.
sarlakani.
Pujari, Rayagada.
Sakhipara.
Jharmunda, Bijubandha, Rourkela.
Khajuribania, Kanika, Hemgiri.
Bolangir.
Tarang.
Jharsuguda.
Laderbahal.
Bhawanipatna.
salepali, Bolangir.
Bolangir.
Jharsuguda.
Sonepur.
Bargarh.
Bhela, Komana, Nuapada.
Kalahandi.
Bolangir.
Sundargarh.
Magurbeda, Bolangir.
Jagatsinghpur.
Colony, Bolangir.
Palsama, Reamala, Deogarh.
Bargarh.
Rourkela.
Julat.
bolangir.
kantmal.
bolangir.
Bolangir.
KANTABANJI, Bolangir.
Pradhanpara.
Magurbeda, Bolangir.
jharbandh.
Nuapada, Riyamal, Deogarh.
Sambalpur, Ainthapali.
township, Rourkela.
Rourkela.
Bargarh.
Budeljore.
Mangaspur, Tangarpali, Sundargarh.
Sundargarh.
Ufula, Pur, Sonepur.
Kutrumali, Kerapai, Rampur, Kalahandi.
Bargarh.
Saling, Muskuti, Narla, Kalahandi.
bagichpara.
Rourkela.
KEGAON, golamunda.
Brahmani.
Sundargarh.
Saldihi, Jharbandh.
Badapujhariguda, Jaypatana, Kalahandi.
Kalahandi.
Nuapada.
Badmal, Jharsuguda.
Gudvela, Balangir.
Garjan, Sundargarh.
Lephripara.
Badapujhariguda, Jaypatana, Kalahandi.
ambabhona.
Rourkela.
boudha.
Dhaner, Kalahandi.
boudha.
Sinapali, Nuapada.
kusumjore, Sinapali, Nuapada.
Angadi, Kandhamal, Seser.
Upparapada.
Palaceline.
Rourkela.
khariar, nuapada.
Lulkidihi, Balisankara, Sundargarh.
Modipara.
Sambalpur.
Bargarh.
Lakhbahali, Lanjigarh.
jhitik, paikmail.
Ragendrapur, Dabha, Jharbandh, Bargarh.
No.
Bargarh, Grid.
Rourkela.
Teliabahal, Jharsuguda.
Titlagarh.
Bargarh.
Bargarh.
majhapara.
Bargarh, Grid.
deogarh.
Bolangir.
Temri, Paikamal, Bargarh.
Asanbani, Anandpur, Kendujhar.
Raisalpadar.
Dehuripala, Palasama, Reamal, Deogarh.
kapsipali, odiapali, Bolangir.
Nagpada, Bargarh.
Sinapali, Nuapada.
Budeljore.
Baghiabandh, Tabada, Reamal, Deogarh.
Tabalbanji, Banipali, Bolangir.
Luhakhan, Jaurumal.
Gailo, Tileibani, Deogarh.
Gariabandha, Bolangir.
Semla, Parla, Dharamgarh, Kalahandi.
Boudh.
Modipara.
942, sanarengali.
bangomunda.
949.
Kalahandi.
Kadamdih, Sundergarh.
15, Dedhasuli, Rampur, Kalahandi.
Rourkela.
Kalahandi, Rampur.
Kukudi, Jayapatna.
Nuapada.
chhendia, DHARMGARH.
Majhagaon, Komna, Nuapada.
Sambalpur, Ainthapali.
Temri, Paikmal, Bargarh.
Nuapada.
Bolangir.
Chandivata.
hole.
Sukhadihi, Jharsuguda.
paralsinga, kesinga, Kalahandi.
Ambabhona.
Jharsuguda.
jharband, bragarh.
paikmail.
Lahunipada.
Rourkela.
panposh.
Sambalpur.
chowk.
Jharsuguda.
Bhawanipatna.
deogarh, Basantpur.
Bolangir.
Jharsuguda.
jaipatna.
Bolangir.
Bharsuja, Agalpur, Bolangir.
Junani, Ambabhona, Bargarh.
Deheripali, Talamendha, Bhoden, Bhargarh.
Junani, Ambabhona, Bargarh.
Dunguripali, Sonepur.
Bargarh, barapali.
tepren, banfpada, deogaon.
Sipur, Karalga, Riyamal, Deogarh.
Hatipali, Bheden, Bargarh.
lemdhar.
bahal, Bonai, Sundergarh.
Bhawanipatna.
Bolangir.
Sundargarh.
Kandhara, Redhakhol, Sambalpur.
Kandpali.
NAC.
Rourkela.
Bolangir.
Silanda, Adabahal, Titlagarh.
Hatipada, Chhamunda, Jujumara, Sambalpur.
Chandnimal, Jujumara, Sambalpur.
RSP.
Titlagarh.
Panposh, Rourkela.
Sambalpur.
Sonepur.
Sadar.
Sambalpur, Naktideol.
Bolangir.
Bolangir.
Khunti, Sambalpur.
Sindhol, Sonepur.
Jharsuguda.
jamujhari, batunga.
sambalpur.
Rourkela.
Dharamgarh, Kalahandi.
Bargarh.
Hirakud.
Gundurupali.
1123, Lakhanpur, Jharsuguda.
Adhamunda, Kalahandi.
Saradha, Jharsuguda.
Adhamunda, Bhawanipatna.
Rourkela.
Bheden, Mahulpali.
Sambalpur, office.
Kokasara.
bareipalichowk, details, a.
C, site, Rourkela.
Sonepur.
1144.
Rourkela.
Rourkela.
Bolangir.
Kanjijharan, Badimal, Lakhanpur.
Sundargarh.
Amatha, Chancher, Kesinga, Kalahandi.
Rourkela.
Rourkela.
town.
or, 1171.
saintala.
saintala.
Temri, Paikmal, Bargarh.
Hadipali, Kuchinda.
Hadipali, Kuchinda.
Hadipali, Kuchinda.
Hadipali, Kuchinda.
Hadipali, Kuchinda.
Seemerta.
Luhakhan, Balangir.
Tileipashi.
Nuasahi, Burda, Redhachhol.
Tileipashi.
Bolangir.
luhakhan, ramchandrapur, deogaon.
luhakhan, ramchandrapur, deogaon.
samadpadar.
samadpadar.
kantamal.
samadpadar.
ainthapali.
Badmal.
nuagaon, komna.
Badapujhariguda, Jaypatana, Kalahandi.
gunagamal, pali, chinched, gudvela, house, madhia.
Bishipali, Padampur, Bargarh.
nuagaon, komna.
Madhiapali, Balangir.
lameibahal, bahal.
Soleguda, Sole, Sundargarh.
Rokal, Boden.
Rourkela.
Sundargarh.
Rourkela.
Ramgarh.
Kandapali, Bargarh.
Gambhari, Belapada.
Rourkela.
kokasara.
kokasara.
kokasara.
kokasara.
Sundergarh.
Sundergarh.
kokasara.
Sundergarh.
tangaripada, karlakot, Nupada.
pokhratoli, buchkupada.
Tangaripada, Karlakot, Boden, Nuapada.
Tangaripada, Karlakote, Boden, Nuapara.
Rourkela.
padar, kumkhal.
plant, Rourkela.
padar, kumkhal.
Bolangir.
Depur, Kalampur, Kalhandi.
Bolangir.
Bolangir.
Khandakata, Kuchinda.
Bolangir.
Tukula, Khariyar.
Kalahandi.
Fitingpada, Lulkidihi, Balishankara, Sundargarh.
Kalahandi.
Kalahandi.
khandakata, kuchinda.
Kulingamala, karangamala, Beden, Nupada.
Kulingamala, karangamala, Beden, Nupada.
putupada, farsara, boden, Nuapada.
barabandha, rampir, Kalahandi.
barabandha, rampir, Kalahandi.
barabandha, rampir, Kalahandi.
Telighana, kandeimunda, kutra, sundergarh.
barabandha, rampir, Kalahandi.
Matanjadi, Barbandha, Kalahandi.
Nuapada.
Nuapada.
Matanjadi, Barbandha, Kalahandi.
Nuapada.
Koksara, Kalahandi.
Bhailadihi, Adasha, Riyamal, Debgarh.
Bhailadihi, Adasha, Riyamal, Debgarh.
Bamra, Sambalpur.
Bisra.
Koksara, Kalahandi.
Varuamunda, Jatagarh, Komana, Nuapada.
chowk.
chhendia, DHARMGARH.
Bharuamunda, Jatagada, Komna, Nuapada.
Duajhar, Khariar, Nuapada.
Duajhar, Khariar, Nuapada.
Thanat, DHARAMGARH, Kalahandi.
Bolangir.
Bolangir.
Bolangir.
Bharuamunda, Jatagada, Komna, Nuapada.
Balangir.
Basupalli, Rengali.
Balangir.
Basupalli, Rengali.
Bharuamunda, Jatagada, Komna, Nuapada.
Balangir.
Tukula, Khariar, Nuapada.
Baialdihi, Adasa, Reamal, Debgarh.
Patnagarh, Bolangir.
Bhaghala, balangir.
Kolkata.
Jharsuguda.
Nabarangpur.
Khiloberni, chadheimara.
Khiloberni, chadheimara.
Khiloberni, chadheimara.
Babupada, saunamara, Balisankara, Sundergarh.
Babupada, saunamara, Balisankara, Sundergarh.
Babupada, saunamara, Balisankara, Sundergarh.
Khiloberni, chadheimara.
Khiloberni, chadheimara.
Nuapada.
Babupada, saunamara, Balisankara, Sundergarh.
Babupada, saunamara, Balisankara, Sundergarh.
Babupada, saunamara, Balisankara, Sundergarh.
Soleguda, Sole, Sundargarh.
Tumbesingha, SMC.
Babupada, saunamara, Balisankara, Sundergarh.
Kalipathar, Karalaga, Reamal, Deogarh.
chhendia, DHARMGARH.
Rourkela.
Patnagarh, Bolangir.
Patnagarh, Bolangir.
Municipality, Jharsuguda.
beteijharan, kantapali, barkote.
beteijharan, kantapali, barkote.
saradhapur.
boden.
Sunabeda, Komana, Nuapada.
various, pankadihi.
boden.
various, pankadihi.
ainthapali.
sahashapur.
kantabahal, Reamal.
sahashapur.
Rayagada.
Bijadihi, Bargarh, point, also.
Gadramunda, Khariar, Nuapada.
Bargarh.
siallati.
siallati.
sahashapur.
Kulingamal, Karangamala, Boden, Nuapada.
Kulingamal, Karangamala, Boden, Nuapada.
Jharsuguda.
Kulingamal, Karangamala, Boden, Nuapada.
Kulingamal, Karangamala, Boden, Nuapada.
Kulingamal, Karangamala, Boden, Nuapada.
Nuadihi, Lariapalli, Bamra, Sambalpur.
Nuadihi, Lariapalli, Bamra, Sambalpur.
Nuadihi, Lariapalli, Bamra, Sambalpur.
Nuadihi, Lariapalli, Bamra, Sambalpur.
Nuadihi, Lariapalli, Bamra, Sambalpur.
Nuadihi, Lariapalli, Bamra, Sambalpur.
Ulikupa, fencing, safety.
Ulikupa, fencing, safety.
Beria.
Nuadihi, Lariapalli, Bamra, Sambalpur.
Babupada, saunamara, Balisankara, Sundergarh.
chwkipara, Jharsuguda.
Jharsuguda.
Jharsuguda.
Rourkela.
his.
Domajhar, Boden, Nuapada.
Domajhar, Boden, Nuapada.
Lanjhi.
Ulikupa.
Kalahandi.
patamunda, koida.
Sadar, Jharsuguda.
patamunda, koida.
janamura, sonpur.
patamunda, koida.
patamunda, koida.
patamunda, koida.
patamunda, koida.
patamunda, koida.
patamunda, koida.
janamura, sonpur.
Boiranga, Boden, Nuapada.
Boiranga, Boden, Nuapada.
patamunda, koida.
his.
Kadamdihi, Patamunda, Koida, Sundargarh.
Padhanpali, Kuhibahal, Binka, Sonepur.
Padhanpali, Kuhibahal, Binka, Sonepur.
Padhanpali, Kuhibahal, Binka, Sonepur.
Chowk, Jharsuguda.
Padhanpali, Kuhibahal, Binka, Sonepur.
Padhanpali, Kuhibahal, Binka, Sonepur.
Bolangir.
Padhanpali, Kuhibahal, Binka, Sonepur.
Bolangir.
Rourkela.
Julat, Kanbar, Barpali, Bargarh.
Sonepur.
litisargi.
Jharsuguda.
Sareikela.
Sareikela.
Bolangir.
Sareikela.
Loisinga, Bolangir.
Loisinga, Bolangir.
Loisinga, Bolangir.
Dumabahal, Sundargarh.
Dumabahal, Sundargarh.
Loisinga, Bolangir.
Loisinga, Bolangir.
Loisinga, Bolangir.
gambharipalli, Atabira.
Alekhapura, Kendrikala, Bonai.
Alekhapura, Kendrikala, Bonai.
gambharipalli, Atabira.
Alekhapura, Kendrikala, Bonai.
Sadar.
uparajhara, Deogaon.
Sadar.
uparajhara, Deogaon.
Sadar.
uparajhara, Deogaon.
Sadar.
dhirmunda.
Riyamal, Deogarh.
bareipali.
bijepur, kharmunda.
bijepur, kharmunda.
uparajhara, Deogaon.
Sadar.
bisipilli.
ghassipada.
jujomura.
varasuja, Bolangir.
Bolangir.
turisimel, malijubanga.
turisimel, malijubanga.
turisimel, malijubanga.
kaishira, barpalli.
kaishira, barpalli.
Bolangir.
1787.
bubel, puintala, pada, tangarapada.
bubel, puintala, pada, tangarapada.
bubel, puintala, pada, tangarapada.
bubel, puintala, pada, tangarapada.
height, to.
height, to.
uparbahal, loisingha.
uparbahal, loisingha.
gundri.
kenjhiriapali.
kenjhiriapali.
Julat, Kanbar, barpali.
point, the.
Mingur, Kalampur, Kalahandi.
Bolangir.
Rourkela.
Badmal.
Badmal.
Rourkela.
Bolangir.
Nuatihura, Maneswar.
Bolangir.
Bolangir.
jharbandh.
Dharanimal, Boden.
Dharanimal, Boden.
Bhawanipatna.
Bolangir.
Bhawanipatna.
Bhawanipatna.
Bhawanipatna.
Bolangir.
Bolangir.
Bolangir.
Bolangir.
Bhawanipatna.
Nuatihura, Maneswar.
Bhawanipatna.
Tiwarigali.
lane.
Jharaberni, Chadheimara, Reamal, Deogarh.
Bhawanipatna.
Jharaberni, Chadheimara, Reamal, Deogarh.
Jharaberni, Chadheimara, Reamal, Deogarh.
Bolangir.
Bhawanipatna.
interior.
Dharanimal, Boden.
Dhankauda.
Dhankauda.
Bolangir.
Koksara, Kalahandi.
Jharbandh, Bargarh.
Jharbandh, Bargarh.
1896.
1897.
Bargarh.
thuamula, Rampur.
Titilagarh, Bolangir.
bijepur.
burubuda, lulang, reamal.
4, gundri.
Jharaberni, Chadheimara, Reamal, Deogarh.
4, gundri.
trilochanpur, lanjhigarh.
Khaichua, lanjhigarh.
Sikuan, Deogaon, Bolangir.
Sundargarh.
site, feedback.
road, demanding.
dungaripalli.
road, demanding.
Boden.
Boden.
bijepur, no, consumer.
Rayagada.
Boden, Nuapada.
KADOPADA, Palsada.
KADOPADA, palsada.
Mandel, Norla.
1998.
Mandel, Norla.
Boden.
road, demanding.
uparjhar, Tusura.
uparjhar, deogaon.
jaypur, bill, demanding, waiver, protest.
nildunguri.
chatrapur, that.
uparjhar, deogaon.
uparjhar, deogaon.
afamara, sarasamala.
uparjhar, deogaon.
uparjhar, deogaon.
jaypur, bhatli, power, bill, demanding, waiver, protest.
Lakhbahali, Lanjigarh.
birmal.
nildunguri.
bijepur.
2036, Bijepur, Bargarh.
2037, Bijepur, Bargarh.
Jharsuguda.
Patarpeni, jamankira.
meghapal.
Sinapali, Nuapada.
meghapal.
girisima, bhograkacha, jharpalam.
meghapal.
Nuapada.
sanagurjivata, karuaajhara, khaprakhol, Bolangir.
sanagurjivata, karuajhar, khaprakhol.
bisipali, kadaligarh.
sanagurjivata, karuajhar, khaprakhol.
balangir.
bisipali, kadaligarh.
kantabahal.
Malpada, Bolangir.
Malpada, Bolangir.
meghpal, jujomara.
konajhirapalli.
Bhawanipatna.
bonai.
meghapal.
bonai.
Bhawanipatna.
Bolangir.
rupa.
Bolangir.
bijepur.
Rangatikra, Laida, Rengali.
Rangatikra, Laida, Rengali.
Rangatikra, Laida, Rengali.
Rishigaon, Bhabanipatna.
Rishigaon, Bhabanipatna.
Kurli, Chuauonka, Turekela, Bolangir.
Patarpeni, jamankira.
Tumura, Golmunda, Kalahandi.
Patarpeni, jamankira.
Padhel, patnagarh, Bolangir.
Saradhapur.
Saradhapur.
badabazaar.
Malibari.
chingerkanta, dunguripali.
chingerkanta, dunguripali.
chingerkanta, dunguripali.
chingerkanta, dunguripali.
chingerkanta, dunguripali.
chingerkanta, dunguripali.
chingerkanta, dunguripali.
chingerkanta, dunguripali.
chingerkanta, dunguripali.
Hirapali, Sohela.
chingerkanta, dunguripali.
LADUGAON, koksara.
chingerkanta, dunguripali.
birmal.
chingerkanta, dunguripali.
Badapujhariguda, Jaypatana, Kalahandi.
Badapujhariguda, Jaypatana, Kalahandi.
Sisakhal.
chingerkanta.
chingerkanta, dunguripali.
karlapita, vundimuhan, sadar, Bolangir.
karlapita, vundimuhan, Bolangir.
Khaprakhol.
dumerguda, pani, MRAMPUR.
Kesinga.
dumerguda, pani, MRAMPUR.
Koraput.
2316.
2321.
bareipali.
Malpada, Bolangir.
Rourkela.
Kujang, Jagatsinghpur.
Bhukta, Bhatli.
Bhukta, Bhatli.
Boudh.
Panimura, 2348.
Naktideol.
Kadaligarh, Sambalpur.
Gudveli, Khariar, Nuapada.
Gudveli, Khariar, Nuapada.
Kadaligarh, Sambalpur.
bhukabeda, tileibani, requested.
bhukabeda, tileibani, requested.
arjunda, banjipali, ambabhona.
bhukabeda, tileibani, requested.
arjunda, banjipali, ambabhona.
bhukabeda, tileibani, requested.
Tunmura, Kutra, Sundargarh.
Ulunda, Raxa.
Badangomunda.
Ulunda, Raxa.
Chakarkend, Bargarh.
Narangpur, bhatli.
Narangpur, bhatli.
AINTHAPALI.
Tikrapada, Bolangir.
Boden, Nuapada.
kalahandi.
2453, medinipur, office, water.

In [ ]:
vilage_df

                                                Location
5                              Haragouirbihar,Sambalpur.
11                                  pradhanpali  bargarh
14     sambalpur. Mr. Amit is asked to share the cont...
25                                - Sinapali dist Nupada
26                                   sindhekela bolangir
...                                                  ...
32866                                     rengali basti.
32867                                     rengali basti.
32868                                             kikia.
32870                               ujalpur, sundargarh.
32872                                          BALAGAON.

[8780 rows x 1 columns]